
// context/LanguageContext.jsx
import React, { createContext, useState, useContext, useEffect, useCallback, useMemo } from 'react';

const defaultTranslations = {
  // Settings
  settings: "Settings",
  robot_id: "ROBOT ID",
  dark_mode: "Dark Mode",
  enable_notifications: "Enable Notifications",
  theme: "Theme",
  language: "Language",
  save: "Save",
  reset: "Reset",
  settings_saved: "Configuration Applied Successfully",
  logout: "Logout",
  notifications: "Notifications",

  // Header
  agvs: "AGVs",
  robot_status: "Robot Status",
  updated: "Updated",
  never: "Never",
  loading: "Loading...",
  wifi_connected: "WiFi Connected",
  wifi_disconnected: "WiFi Disconnected",
  select_online: "Select Online",
  clear: "Clear",
  search_agvs: "Search AGVs...",
  agvs_selected: "AGVs selected",
  cancel: "Cancel",
  confirm: "Confirm",

  // Sidebar
  missioncontrol: "Mission Control",
  playpause: "Play/Pause",
  dashboard: "Dashboard",
  magnetic: "Interlock Dashboard",
  qrcode: "QR Code",
  maps: "Maps",
  realtime_visualisation: "Real-Time Visualisation",
  task_allocation: "Task Allocation",
  health_check: "Health Check",
  reports: "Reports",
  mapview: "Map View",

  // Footer
  copyright: "© 2025 Taikisha India | All Rights Reserved.",

  // Dashboard
  system_status: "System Status",
  ros_bridge: "ROS Bridge",
  stations_loaded: "Stations Loaded",
  current_location: "Current Location",
  target_location: "Target Location",
  amr_status_distribution: "AMR Status Distribution",
  battery_level_overview: "Battery Level Overview",
  amr_status: "AMR Status",
  station_information: "Station Information",

  // Status
  online: "Online",
  offline: "Offline",
  running: "Running",
  idle: "Idle",
  maintenance: "Maintenance",
  charging: "Charging",

  // Table headers
  amr_id: "AMR ID",
  status: "Status",
  battery: "Battery",
  motor_temp: "Motor Temp",
  speed: "Speed",
  error: "Error",

  // ── MISSION CONTROL ──────────────────────────────────────
  mission_control: {
    title:               "Mission Control",
    online:              "Online",
    offline:             "Offline",
    mission_trigger:     "Mission Trigger",
    triggering:          "Triggering...",
    mission_file:        "Mission File",
    select_mission:      "Select a mission...",
    missions_count:      "mission(s)",
    waiting_list:        "Waiting for mission list from robot...",
    start_mission:       "Start Mission",
    starting:            "Starting...",
    missions_from_robot: "mission(s) from robot",
    connect_to_see:      "Connect to robot to see available missions",
    loaded_badge:        "loaded",
    loaded_mission:      "Loaded Mission",
    none:                "None",
    state:               "State",
    target_tag:          "Target Tag",
    speed_label:         "Speed",
    progress:            "Progress",
    action:              "Action",
    idle_action:         "IDLE",
        direction:           "Direction",
    mission_progress:    "Mission Progress",
    safety_label:        "Safety",
    safety_active:       "ACTIVE — HALTED",
    safety_clear:        "CLEAR — NORMAL",
    safety_warning:      "⚠ Motion disabled until safety clears.",
    safety_banner:       "⚠ SAFETY ACTIVE — MOTION HALTED ⚠",
    start:               "Start",
    pause:               "Pause",
    resume:              "Resume",
    abort:               "Abort",
    reset_mission:       "Reset Mission",
    unload_mission:      "Unload Mission",
    status_online:       "● ONLINE",
    status_offline:      "○ OFFLINE",
    no_signal:           "NO SIGNAL",
    center_tag:          "CENTER TAG",
    ready:               "READY ✓",
    center_tag_btn:      "Center Tag",
    center_tag_hint:     "Click \"Center Tag\" to align",
    align_backward:      "Move robot BACKWARD",
    align_forward:       "Move robot FORWARD",
    align_right:         "Move robot RIGHT",
    align_left:          "Move robot LEFT",
    align_finetune:      "Fine-tune position",
    align_detail_y_back: "mm — move backward until Y is between -1 and +1 mm",
    align_detail_y_fwd:  "mm — move forward until Y is between -1 and +1 mm",
    align_detail_x_right:"mm — move right until X is between -1 and +1 mm",
    align_detail_x_left: "mm — move left until X is between -1 and +1 mm",
    align_detail_fine:   "mm — nudge slowly until both are between -1 and +1",
    watchdog_title:      "WATCHDOG FAULT",
    watchdog_details:    "ERROR DETAILS",
    watchdog_missed_tag: "Missed Tag:",
    watchdog_last_tag:   "Last Seen Tag:",
    watchdog_distance:   "Distance Traveled:",
    watchdog_time:       "Time:",
    watchdog_reset:      "Reset Mission",
    watchdog_dismiss:    "Dismiss",
    watchdog_info:       "Robot failed to detect tag",
    watchdog_after:      "after traveling",
    watchdog_from:       "from tag",
    watchdog_check:      "Adjust robot on tag and then press reset button on screen.",
    no_mission_trigger:  "No mission loaded to trigger",
    trigger_success:     "Mission triggered successfully!",
    trigger_failed:      "Failed to trigger mission",
    trigger_error:       "Trigger error:",
    connected_toast:     "Connected to robot",
    system_offline:      "System offline",
    offline_no_load:     "System offline - cannot load mission",
    select_first:        "Please select a mission first",
    loaded_success:      "loaded successfully",
    load_failed:         "Failed to load",
    error_prefix:        "Error:",
    unknown_error:       "Unknown",
    command_sent:        "Command sent",
    command_failed:      "Command failed",
    mission_started:     "Mission started",
    mission_paused:      "Mission paused",
    mission_resumed:     "Mission resumed",
    mission_aborted:     "Mission aborted",
    mission_reset:       "Mission reset",
    mission_unloaded:    "Mission unloaded",
  },

  // Health
  health: {
    amr: "AMR",
    imu: "IMU",
    lidar: "LIDAR",
    camera: "Depth Camera",
    battery: "Battery",
    motor: "Motor Controller",
    front_estop: "Front Estop",
    rear_estop: "Rear Estop",
    encoder: "Encoder",
    brakes: "Brakes",
    cpu: "CPU Usage",
    memory: "Memory Usage",
    disk: "Disk Usage",
    ros2: "ROS2 Nodes",
    ros2t: "ROS2 Topics",
    nav2: "Nav2 Stack",
    localization: "Localization",
    pathplanner: "Path Planner",
    rosmaster: "ROS Master",
    wifi: "WiFi Connection",
    ethernet: "Ethernet",
    serial: "Serial Communication",
    can: "CAN Communication",
    position: "Position",
    pendant_workover: "Workover",
    front_estop1: "E-Stop  Front",
    front_estop2: "E-Stop  Front",
    rear_estop1: "E-Stop  Rear",
    rear_estop2: "E-Stop  Rear",
    pendant_estop: "E-Stop Pendant",
    fault_reset: "Fault Reset",
    front_lidar: "Front Lidar",
    rear_lidar: "Rear Lidar",
    front_bumper: "Bumper Front",
    rear_bumper: "Bumper Rear",
    auto_mode: "Auto Mode",
    manual_mode: "Manual Mode",
    safety_interlocks: "Safety & Interlocks",
    lcp_mls_status: "LCP & MLS Status",
    lcp1: "LCP 1", lcp2: "LCP 2", lcp3: "LCP 3",
    mls: "MLS",
    magnetic_agv: "Magnetic AGV",
    plc_status: "PLC Status",
    work_over: "Work Over",
    back_estop: "Back Estop",
    back_lidar: "Back Lidar",
    status: { ok: "OK", fault: "FAULT", idle: "IDLE", unknown: "UNKNOWN", green: "GREEN", red: "RED" },
  },

  // ── REPORTS ──────────────────────────────────────────────
  report: {
    title:                    "Reports",
    subtitle:                 "Safety interlock events & mission status history",
    rolling_window:           "rolling",
    record_window:            "record window",

    // Buttons
    btn_interlock:            "Interlock",
    btn_mission:              "Mission",
    btn_completed:            "Completed",
    btn_combined:             "Combined",
    btn_clear:                "Clear",

    // Connection banner
    robot_online:             "Online",
    robot_disconnected:       "Disconnected",
    state_label:              "State:",
    waiting_wifi:             "⚠ Waiting for WiFi",

    // Summary cards
    card_interlock:           "Interlock",
    card_int_faults:          "Interlock Faults",
    card_mission:             "Mission",
    card_msn_faults:          "Mission Faults",
    card_tag_miss:            "Tag Miss",
    card_complete:            "Complete",

    // Tabs
    tab_interlock:            "Interlock",
    tab_mission:              "Mission",
    tab_completed:            "Completed",
    tab_miss_suffix:          "⚠",

    // Panel headers
    panel_interlock:          "🔒 Interlock Event History",
    panel_mission:            "🚀 Mission Status History",
    panel_completed:          "✅ Completed Missions",
    records_label:            "records",

    // Rolling badge
    badge_rolling:            "· ROLLING",
    badge_tooltip_full:       "Rolling window active — oldest record is dropped when a new one arrives",
    badge_tooltip_slots:      "slot(s) remaining before rolling starts",

    // Empty states
    empty_interlock_label:    "No interlock events recorded yet",
    empty_interlock_sub:      "Events appear when safety signals change state",
    empty_mission_label:      "No mission state changes recorded yet",
    empty_mission_sub:        "Events appear when mission state changes or a tag miss is detected",
    empty_completed_label:    "No completed missions yet",
    empty_completed_sub:      "A summary row is added each time a mission reaches the COMPLETE state",

    // Interlock table headers
    col_sr:                   "SR",
    col_timestamp:            "Timestamp",
    col_signal:               "Signal",
    col_status:               "Status",
    col_health:               "Health",
    col_value:                "Value",

    // Interlock table values
    val_active:               "⚠️ Active",
    val_normal:               "✅ Normal",
    val_fault_active:         "⚠️ Fault Triggered",
    val_healthy:              "✅ Healthy",

    // Mission table headers
    col_state:                "State",
    col_tag_miss:             "Tag Miss",
    col_expected_got:         "Expected→Got",
    col_mission_file:         "Mission File",
    col_progress:             "Progress",
    col_speed:                "Speed",
    col_action:               "Action",
    col_safety:               "Safety",
    col_dist:                 "Dist (m)",

    // Mission table values
    val_miss:                 "⚠️ MISS",
    val_safety_active:        "⚠️ ACTIVE",
    val_safety_clear:         "✅ CLEAR",

    // Completed table headers
    col_completed_at:         "Completed At",
    col_total_steps:          "Total Steps",
    col_distance:             "Distance (m)",
    col_duration:             "Duration",
    col_loop:                 "Loop",
    val_steps_suffix:         "steps",
    val_loop_on:              "🔁 ON",
    val_loop_off:             "— OFF",

    // Stats footer — interlock
    stat_total_events:        "Total Events",
    stat_healthy:             "Healthy",
    stat_faults:              "Faults",

    // Stats footer — mission
    stat_state_changes:       "State Changes",
    stat_tag_misses:          "Tag Misses",
    stat_missions:            "Missions",
    stat_complete:            "Complete",

    // Stats footer — completed
    stat_total_runs:          "Total Runs",
    stat_avg_steps:           "Avg Steps",
    stat_avg_dist:            "Avg Dist (m)",
    stat_loop_runs:           "Loop Runs",

    // Alerts / confirms
    alert_no_interlock:       "No interlock events recorded yet.",
    alert_no_mission:         "No mission events recorded yet.",
    alert_no_completed:       "No completed missions recorded yet.",
    alert_no_data:            "No events recorded yet.",
    confirm_clear_all:        "Clear ALL reports (interlock + mission + completed)?",

    // CSV headers
    csv_interlock_title:      "SAFETY INTERLOCK EVENTS REPORT",
    csv_mission_title:        "MISSION STATUS EVENTS REPORT",
    csv_completed_title:      "COMPLETED MISSIONS REPORT",
    csv_generated:            "Generated:",
    csv_showing_last:         "Showing last",
    csv_records_rolling:      "records (rolling window)",
    csv_records_completed:    "completed missions",
    csv_tag_misses:           "Tag Misses:",
    csv_val_active:           "Active",
    csv_val_normal:           "Normal",
    csv_val_active_trig:      "Active/Triggered",
    csv_val_inactive:         "Inactive/Normal",
    csv_val_yes:              "YES",
    csv_val_no:               "NO",
    csv_val_on:               "ON",
    csv_val_off:              "OFF",
  },

  // Task Allocation
  configure_task: "Configure Task",
  configure_task_desc: "Configure the selected task parameters",
  mission_builder: "Mission Builder",
  loop: "Loop",
  infinite_loop: "(-1 = infinite)",
  clear_all: "Clear All",
  select_robot: "Select Robot",
  drag_tasks_prompt: "Drag task modules here to build mission",
  total_tasks: "Total Tasks",
  send_mission: "Send Mission",
  tasks: "tasks",
  available_tasks: "Available Tasks",
  drag_drop_prompt: "Drag and drop to add tasks to mission",
  backend_status: "Backend Status",
  connected: "Connected",
  disconnected: "Disconnected",
  select_task: "Select a task to configure",
  configure: "Configure",
  direction: "Direction",
  forward: "Forward",
  reverse: "Reverse",
  clockwise: "Clockwise",
  anticlockwise: "Anticlockwise",
  distance_meters: "Distance (meters)",
  speed_ms: "Speed (m/s)",
  rotation_angle: "Rotation Angle (degrees)",
  angular_speed: "Angular Speed (r/s)",
  zone: "Zone",
  duration_ms: "Duration (milliseconds)",
  backend_not_connected: "Backend not connected",
  select_robot_prompt: "Please select a robot",
  add_task_prompt: "Add at least one task",
  mission_queued: "Mission queued successfully",
  mission_failed: "Failed to send mission",
};


// ── MARATHI ──────────────────────────────────────────────────
const mrTranslations = {
  settings: "सेटिंग्ज",
  robot_id: "रोबोट आयडी",
  dark_mode: "डार्क मोड",
  enable_notifications: "सूचना सक्षम करा",
  language: "भाषा",
  theme: "थीम",
  save: "जतन करा",
  reset: "रीसेट करा",
  settings_saved: "सेटिंग्ज यशस्वीरित्या जतन केल्या!",
  logout: "लॉग आउट",
  notifications: "सूचना",
  agvs: "एजीव्ही",
  robot_status: "रोबोट स्थिती",
  updated: "अपडेट केले",
  never: "कधीही नाही",
  loading: "लोड होत आहे...",
  wifi_connected: "WiFi कनेक्ट केले",
  wifi_disconnected: "WiFi डिस्कनेक्ट केले",
  select_online: "ऑनलाइन निवडा",
  clear: "साफ करा",
  search_agvs: "एजीव्ही शोधा...",
  agvs_selected: "एजीव्ही निवडले",
  cancel: "रद्द करा",
  confirm: "पुष्टी करा",
  missioncontrol: "मिशन नियंत्रण",
  playpause: "प्ले/पॉज",
  dashboard: "डॅशबोर्ड",
  magnetic: "इंटरलॉक डॅशबोर्ड",
  qrcode: "क्यूआर कोड",
  maps: "नकाशे",
  realtime_visualisation: "रीयल-टाइम व्हिज्युअलायझेशन",
  task_allocation: "कार्य वाटप",
  health_check: "आरोग्य तपासणी",
  reports: "अहवाल",
  mapview: "नकाशा दृश्य",
  copyright: "© २०२५ ताइकिशा इंडिया | सर्व हक्क राखीव.",
  system_status: "सिस्टम स्थिती",
  ros_bridge: "ROS ब्रिज",
  stations_loaded: "स्टेशने लोड केली",
  current_location: "सध्याचे स्थान",
  target_location: "लक्ष्य स्थान",
  amr_status_distribution: "एएमआर स्थिती वितरण",
  battery_level_overview: "बॅटरी पातळी अवलोकन",
  amr_status: "एएमआर स्थिती",
  station_information: "स्टेशन माहिती",
  online: "ऑनलाइन",
  offline: "ऑफलाइन",
  running: "चालू",
  idle: "निष्क्रिय",
  maintenance: "देखभाल",
  charging: "चार्जिंग",
  amr_id: "एएमआर आयडी",
  status: "स्थिती",
  battery: "बॅटरी",
  motor_temp: "मोटर तापमान",
  speed: "गती",
  error: "त्रुटी",

  mission_control: {
    title:               "मिशन नियंत्रण",
    online:              "ऑनलाइन",
    offline:             "ऑफलाइन",
    mission_trigger:     "मिशन ट्रिगर",
    triggering:          "ट्रिगर होत आहे...",
    mission_file:        "मिशन फाइल",
    select_mission:      "मिशन निवडा...",
    missions_count:      "मिशन(ने)",
    waiting_list:        "रोबोटकडून मिशन यादीची प्रतीक्षा...",
    start_mission:       "मिशन सुरू करा",
    starting:            "सुरू होत आहे...",
    missions_from_robot: "रोबोटकडून मिशन(ने)",
    connect_to_see:      "उपलब्ध मिशन पाहण्यासाठी रोबोटशी जोडा",
    loaded_badge:        "लोड केलेले",
    loaded_mission:      "लोड केलेले मिशन",
    none:                "काहीही नाही",
    state:               "स्थिती",
    target_tag:          "लक्ष्य टॅग",
    speed_label:         "गती",
    progress:            "प्रगती",
    action:              "क्रिया",
    idle_action:         "निष्क्रिय",
        direction:           "दिशा",
    mission_progress:    "मिशन प्रगती",
    safety_label:        "सुरक्षा",
    safety_active:       "सक्रिय — थांबलेले",
    safety_clear:        "स्पष्ट — सामान्य",
    safety_warning:      "⚠ सुरक्षा स्थिती स्पष्ट होईपर्यंत हालचाल अक्षम.",
    safety_banner:       "⚠ सुरक्षा सक्रिय — हालचाल थांबली ⚠",
    start:               "सुरू करा",
    pause:               "थांबवा",
    resume:              "पुन्हा सुरू करा",
    abort:               "रद्द करा",
    reset_mission:       "मिशन रीसेट करा",
    unload_mission:      "मिशन अनलोड करा",
    status_online:       "● ऑनलाइन",
    status_offline:      "○ ऑफलाइन",
    no_signal:           "सिग्नल नाही",
    center_tag:          "टॅग मध्यभागी करा",
    ready:               "तयार ✓",
    center_tag_btn:      "टॅग मध्यभागी करा",
    center_tag_hint:     "संरेखित करण्यासाठी \"टॅग मध्यभागी करा\" वर क्लिक करा",
    align_backward:      "रोबोट मागे न्या",
    align_forward:       "रोबोट पुढे न्या",
    align_right:         "रोबोट उजवीकडे न्या",
    align_left:          "रोबोट डावीकडे न्या",
    align_finetune:      "स्थान सूक्ष्म-समायोजित करा",
    align_detail_y_back: "मिमी — Y -1 ते +1 मिमी दरम्यान येईपर्यंत मागे जा",
    align_detail_y_fwd:  "मिमी — Y -1 ते +1 मिमी दरम्यान येईपर्यंत पुढे जा",
    align_detail_x_right:"मिमी — X -1 ते +1 मिमी दरम्यान येईपर्यंत उजवीकडे जा",
    align_detail_x_left: "मिमी — X -1 ते +1 मिमी दरम्यान येईपर्यंत डावीकडे जा",
    align_detail_fine:   "मिमी — दोन्ही -1 ते +1 दरम्यान येईपर्यंत हळूहळू समायोजित करा",
    watchdog_title:      "वॉचडॉग दोष",
    watchdog_details:    "त्रुटी तपशील",
    watchdog_missed_tag: "चुकलेला टॅग:",
    watchdog_last_tag:   "शेवटचा पाहिलेला टॅग:",
    watchdog_distance:   "प्रवास केलेले अंतर:",
    watchdog_time:       "वेळ:",
    watchdog_reset:      "मिशन रीसेट करा",
    watchdog_dismiss:    "बंद करा",
    watchdog_info:       "रोबोट टॅग शोधण्यात अयशस्वी",
    watchdog_after:      "प्रवास केल्यानंतर",
    watchdog_from:       "टॅगपासून",
    watchdog_check:      "चुकलेल्या टॅगवर रोबोट ॲडजस्ट करा आणि त्यानंतर स्क्रीनवरील 'रिसेट' बटण दाबा.",
    no_mission_trigger:  "ट्रिगर करण्यासाठी कोणतेही मिशन लोड नाही",
    trigger_success:     "मिशन यशस्वीरित्या ट्रिगर झाले!",
    trigger_failed:      "मिशन ट्रिगर करण्यात अयशस्वी",
    trigger_error:       "ट्रिगर त्रुटी:",
    connected_toast:     "रोबोटशी कनेक्ट झाले",
    system_offline:      "सिस्टम ऑफलाइन",
    offline_no_load:     "सिस्टम ऑफलाइन — मिशन लोड करता येत नाही",
    select_first:        "कृपया आधी मिशन निवडा",
    loaded_success:      "यशस्वीरित्या लोड केले",
    load_failed:         "लोड करण्यात अयशस्वी",
    error_prefix:        "त्रुटी:",
    unknown_error:       "अज्ञात",
    command_sent:        "आदेश पाठवला",
    command_failed:      "आदेश अयशस्वी",
    mission_started:     "मिशन सुरू झाले",
    mission_paused:      "मिशन थांबवले",
    mission_resumed:     "मिशन पुन्हा सुरू झाले",
    mission_aborted:     "मिशन रद्द केले",
    mission_reset:       "मिशन रीसेट झाले",
    mission_unloaded:    "मिशन अनलोड झाले",
  },

  health: {
    amr: "एएमआर", imu: "आयएमयू", lidar: "लिडार", camera: "खोली कॅमेरा",
    battery: "बॅटरी", motor: "मोटर कंट्रोलर",
    front_estop: "समोर आणीबाणी बटण", rear_estop: "मागील आणीबाणी बटण",
    encoder: "एन्कोडर", brakes: "ब्रेक्स",
    cpu: "सीपीयू वापर", memory: "मेमरी वापर", disk: "डिस्क वापर",
    ros2: "ROS2 नोड्स", ros2t: "ROS2 टॉपिक्स", nav2: "Nav2 स्टॅक",
    localization: "स्थाननिर्धारण", pathplanner: "मार्ग नियोजक",
    rosmaster: "ROS मास्टर", wifi: "वाय-फाय कनेक्शन",
    ethernet: "ईथरनेट", serial: "सीरियल कम्युनिकेशन", can: "CAN कम्युनिकेशन",
    position: "स्थान", pendant_workover: "पेंडंट वर्कओव्हर",
    front_estop1: "आणीबाणी बटण १ समोर", front_estop2: "आणीबाणी बटण २ समोर",
    rear_estop1: "आणीबाणी बटण १ मागे", rear_estop2: "आणीबाणी बटण २ मागे",
    pendant_estop: "पेंडंट आणीबाणी बटण", fault_reset: "फॉल्ट रीसेट",
    front_lidar: "समोर लिडार", rear_lidar: "मागील लिडार",
    front_bumper: "समोर बंपर", rear_bumper: "मागील बंपर",
    auto_mode: "ऑटो मोड", manual_mode: "मॅन्युअल मोड",
    safety_interlocks: "सुरक्षा इंटरलॉक", lcp_mls_status: "एलसीपी आणि एमएलएस स्थिती",
    lcp1: "एलसीपी १", lcp2: "एलसीपी २", lcp3: "एलसीपी ३", mls: "एमएलएस",
    magnetic_agv: "मॅग्नेटिक एजीव्ही", plc_status: "पीएलसी स्थिती",
    work_over: "वर्क ओव्हर", back_estop: "मागील आणीबाणी बटण", back_lidar: "मागील लिडार",
    status: { ok: "ठीक", fault: "दोष", idle: "निष्क्रिय", unknown: "अज्ञात", green: "हिरवा", red: "लाल" },
  },

  // ── REPORTS (Marathi) ─────────────────────────────────────
  report: {
    title:                    "अहवाल",
    subtitle:                 "सुरक्षा इंटरलॉक घटना आणि मिशन स्थिती इतिहास",
    rolling_window:           "रोलिंग",
    record_window:            "रेकॉर्ड विंडो",
    btn_interlock:            "इंटरलॉक",
    btn_mission:              "मिशन",
    btn_completed:            "पूर्ण",
    btn_combined:             "एकत्रित",
    btn_clear:                "साफ करा",
    robot_online:             "ऑनलाइन",
    robot_disconnected:       "डिस्कनेक्ट",
    state_label:              "स्थिती:",
    waiting_wifi:             "⚠ WiFi ची प्रतीक्षा",
    card_interlock:           "इंटरलॉक",
    card_int_faults:          "इं. दोष",
    card_mission:             "मिशन",
    card_msn_faults:          "मि. दोष",
    card_tag_miss:            "टॅग मिस",
    card_complete:            "पूर्ण",
    tab_interlock:            "इंटरलॉक",
    tab_mission:              "मिशन",
    tab_completed:            "पूर्ण",
    tab_miss_suffix:          "⚠",
    panel_interlock:          "🔒 इंटरलॉक घटना इतिहास",
    panel_mission:            "🚀 मिशन स्थिती इतिहास",
    panel_completed:          "✅ पूर्ण मिशन",
    records_label:            "नोंदी",
    badge_rolling:            "· रोलिंग",
    badge_tooltip_full:       "रोलिंग विंडो सक्रिय — नवीन नोंद येताच जुनी काढली जाते",
    badge_tooltip_slots:      "रोलिंग सुरू होण्यापूर्वी उरलेले स्लॉट",
    empty_interlock_label:    "अद्याप कोणतीही इंटरलॉक घटना नाही",
    empty_interlock_sub:      "सुरक्षा सिग्नल बदलल्यावर घटना दिसतात",
    empty_mission_label:      "अद्याप कोणतेही मिशन बदल नाहीत",
    empty_mission_sub:        "मिशन स्थिती बदलल्यावर किंवा टॅग मिस झाल्यावर घटना दिसतात",
    empty_completed_label:    "अद्याप कोणतेही पूर्ण मिशन नाही",
    empty_completed_sub:      "मिशन COMPLETE स्थितीत पोहोचल्यावर सारांश जोडला जातो",
    col_sr:                   "क्र.",
    col_timestamp:            "वेळ",
    col_signal:               "सिग्नल",
    col_status:               "स्थिती",
    col_health:               "आरोग्य",
    col_value:                "मूल्य",
    val_active:               "⚠️ सक्रिय",
    val_normal:               "✅ सामान्य",
    val_fault_active:         "⚠️ दोष उद्भवला",
    val_healthy:              "✅ निरोगी",
    col_state:                "स्थिती",
    col_tag_miss:             "टॅग मिस",
    col_expected_got:         "अपेक्षित→मिळाले",
    col_mission_file:         "मिशन फाइल",
    col_progress:             "प्रगती",
    col_speed:                "गती",
    col_action:               "क्रिया",
    col_safety:               "सुरक्षा",
    col_dist:                 "अंतर (मी)",
    val_miss:                 "⚠️ मिस",
    val_safety_active:        "⚠️ सक्रिय",
    val_safety_clear:         "✅ स्पष्ट",
    col_completed_at:         "पूर्ण झाले",
    col_total_steps:          "एकूण पायऱ्या",
    col_distance:             "अंतर (मी)",
    col_duration:             "कालावधी",
    col_loop:                 "लूप",
    val_steps_suffix:         "पायऱ्या",
    val_loop_on:              "🔁 चालू",
    val_loop_off:             "— बंद",
    stat_total_events:        "एकूण घटना",
    stat_healthy:             "निरोगी",
    stat_faults:              "दोष",
    stat_state_changes:       "स्थिती बदल",
    stat_tag_misses:          "टॅग मिस",
    stat_missions:            "मिशन",
    stat_complete:            "पूर्ण",
    stat_total_runs:          "एकूण धावा",
    stat_avg_steps:           "सरासरी पायऱ्या",
    stat_avg_dist:            "सरासरी अंतर (मी)",
    stat_loop_runs:           "लूप धावा",
    alert_no_interlock:       "अद्याप कोणतीही इंटरलॉक घटना नाही.",
    alert_no_mission:         "अद्याप कोणतेही मिशन घटना नाहीत.",
    alert_no_completed:       "अद्याप कोणतेही पूर्ण मिशन नाही.",
    alert_no_data:            "अद्याप कोणतीही घटना नाही.",
    confirm_clear_all:        "सर्व अहवाल साफ करायचे (इंटरलॉक + मिशन + पूर्ण)?",
    csv_interlock_title:      "सुरक्षा इंटरलॉक घटना अहवाल",
    csv_mission_title:        "मिशन स्थिती घटना अहवाल",
    csv_completed_title:      "पूर्ण मिशन अहवाल",
    csv_generated:            "तयार केले:",
    csv_showing_last:         "शेवटचे दाखवत आहे",
    csv_records_rolling:      "नोंदी (रोलिंग विंडो)",
    csv_records_completed:    "पूर्ण मिशन",
    csv_tag_misses:           "टॅग मिस:",
    csv_val_active:           "सक्रिय",
    csv_val_normal:           "सामान्य",
    csv_val_active_trig:      "सक्रिय/ट्रिगर",
    csv_val_inactive:         "निष्क्रिय/सामान्य",
    csv_val_yes:              "होय",
    csv_val_no:               "नाही",
    csv_val_on:               "चालू",
    csv_val_off:              "बंद",
  },

  configure_task: "कार्य कॉन्फिगर करा",
  configure_task_desc: "निवडलेल्या कार्याचे पॅरामीटर्स कॉन्फिगर करा",
  mission_builder: "मिशन बिल्डर",
  loop: "लूप", infinite_loop: "(-१ = अनंत)",
  clear_all: "सर्व साफ करा", select_robot: "रोबोट निवडा",
  drag_tasks_prompt: "मिशन तयार करण्यासाठी कार्य मॉड्यूल येथे ड्रॅग करा",
  total_tasks: "एकूण कार्ये", send_mission: "मिशन पाठवा",
  tasks: "कार्ये", available_tasks: "उपलब्ध कार्ये",
  drag_drop_prompt: "मिशनमध्ये कार्ये जोडण्यासाठी ड्रॅग आणि ड्रॉप करा",
  backend_status: "बॅकएंड स्थिती",
  connected: "कनेक्ट केलेले", disconnected: "डिस्कनेक्ट केलेले",
  select_task: "कॉन्फिगर करण्यासाठी कार्य निवडा", configure: "कॉन्फिगर करा",
  direction: "दिशा", forward: "पुढे", reverse: "मागे",
  clockwise: "घड्याळाच्या दिशेने", anticlockwise: "घड्याळाच्या विरुद्ध दिशेने",
  distance_meters: "अंतर (मीटर)", speed_ms: "गती (मी/से)",
  rotation_angle: "रोटेशन कोन (अंश)", angular_speed: "कोनीय गती (आर/से)",
  zone: "झोन", duration_ms: "कालावधी (मिलिसेकंद)",
  backend_not_connected: "बॅकएंड कनेक्ट केलेले नाही",
  select_robot_prompt: "कृपया रोबोट निवडा",
  add_task_prompt: "किमान एक कार्य जोडा",
  mission_queued: "मिशन यशस्वीरित्या रांगेत जोडले",
  mission_failed: "मिशन पाठविण्यात अयशस्वी",
};

// ── HINDI ────────────────────────────────────────────────────
const hiTranslations = {
  settings: "सेटिंग्स", robot_id: "रोबोट आईडी", dark_mode: "डार्क मोड",
  enable_notifications: "सूचनाएं सक्षम करें", language: "भाषा", theme: "थीम",
  save: "सहेजें", reset: "रीसेट करें", settings_saved: "सेटिंग्स सफलतापूर्वक सहेजी गईं!",
  logout: "लॉग आउट", notifications: "सूचनाएं",
  agvs: "एजीवी", robot_status: "रोबोट स्थिति",
  updated: "अपडेट किया गया", never: "कभी नहीं", loading: "लोड हो रहा है...",
  wifi_connected: "WiFi जुड़ा हुआ", wifi_disconnected: "WiFi डिस्कनेक्ट किया गया",
  select_online: "ऑनलाइन चुनें", clear: "साफ करें",
  search_agvs: "एजीवी खोजें...", agvs_selected: "एजीवी चुने गए",
  cancel: "रद्द करें", confirm: "पुष्टि करें",
  missioncontrol: "मिशन नियंत्रण", playpause: "प्ले/पॉज",
  dashboard: "डैशबोर्ड", magnetic: "इंटरलॉक डैशबोर्ड",
  qrcode: "क्यूआर कोड", maps: "मानचित्र",
  realtime_visualisation: "रियल-टाइम विज़ुअलाइज़ेशन",
  task_allocation: "कार्य आवंटन", health_check: "स्वास्थ्य जांच",
  reports: "रिपोर्ट", mapview: "मानचित्र दृश्य",
  copyright: "© २०२५ ताइकिशा इंडिया | सर्व अधिकार सुरक्षित।",
  system_status: "सिस्टम स्थिति", ros_bridge: "ROS ब्रिज",
  stations_loaded: "स्टेशन लोड किए गए",
  current_location: "वर्तमान स्थान", target_location: "लक्ष्य स्थान",
  amr_status_distribution: "एएमआर स्थिति वितरण",
  battery_level_overview: "बैटरी स्तर अवलोकन",
  amr_status: "एएमआर स्थिति", station_information: "स्टेशन सूचना",
  online: "ऑनलाइन", offline: "ऑफलाइन", running: "चल रहा है",
  idle: "निष्क्रिय", maintenance: "रखरखाव", charging: "चार्जिंग",
  amr_id: "एएमआर आईडी", status: "स्थिति", battery: "बैटरी",
  motor_temp: "मोटर तापमान", speed: "गति", error: "त्रुटि",

  mission_control: {
    title:               "मिशन नियंत्रण",
    online:              "ऑनलाइन",
    offline:             "ऑफलाइन",
    mission_trigger:     "मिशन ट्रिगर",
    triggering:          "ट्रिगर हो रहा है...",
    mission_file:        "मिशन फ़ाइल",
    select_mission:      "मिशन चुनें...",
    missions_count:      "मिशन",
    waiting_list:        "रोबोट से मिशन सूची की प्रतीक्षा...",
    start_mission:       "मिशन शुरू करें",
    starting:            "शुरू हो रहा है...",
    missions_from_robot: "रोबोट से मिशन",
    connect_to_see:      "उपलब्ध मिशन देखने के लिए रोबोट से जुड़ें",
    loaded_badge:        "लोड किया गया",
    loaded_mission:      "लोड किया मिशन",
    none:                "कोई नहीं",
    state:               "स्थिति",
    target_tag:          "लक्ष्य टैग",
    speed_label:         "गति",
    progress:            "प्रगति",
    action:              "क्रिया",
    idle_action:         "निष्क्रिय",
        direction:           "दिशा",
    mission_progress:    "मिशन प्रगति",
    safety_label:        "सुरक्षा",
    safety_active:       "सक्रिय — रुका हुआ",
    safety_clear:        "स्पष्ट — सामान्य",
    safety_warning:      "⚠ सुरक्षा स्थिति स्पष्ट होने तक गति अक्षम है।",
    safety_banner:       "⚠ सुरक्षा सक्रिय — गति रुकी ⚠",
    start:               "शुरू करें",
    pause:               "रोकें",
    resume:              "फिर शुरू करें",
    abort:               "रद्द करें",
    reset_mission:       "मिशन रीसेट करें",
    unload_mission:      "मिशन अनलोड करें",
    status_online:       "● ऑनलाइन",
    status_offline:      "○ ऑफलाइन",
    no_signal:           "कोई सिग्नल नहीं",
    center_tag:          "टैग केंद्रित करें",
    ready:               "तैयार ✓",
    center_tag_btn:      "टैग केंद्रित करें",
    center_tag_hint:     "संरेखित करने के लिए \"टैग केंद्रित करें\" पर क्लिक करें",
    align_backward:      "रोबोट पीछे ले जाएं",
    align_forward:       "रोबोट आगे ले जाएं",
    align_right:         "रोबोट दाएं ले जाएं",
    align_left:          "रोबोट बाएं ले जाएं",
    align_finetune:      "स्थिति को सूक्ष्म-समायोजित करें",
    align_detail_y_back: "मिमी — Y को -1 से +1 मिमी के बीच आने तक पीछे जाएं",
    align_detail_y_fwd:  "मिमी — Y को -1 से +1 मिमी के बीच आने तक आगे जाएं",
    align_detail_x_right:"मिमी — X को -1 से +1 मिमी के बीच आने तक दाएं जाएं",
    align_detail_x_left: "मिमी — X को -1 से +1 मिमी के बीच आने तक बाएं जाएं",
    align_detail_fine:   "मिमी — दोनों के -1 से +1 के बीच आने तक धीरे-धीरे समायोजित करें",
    watchdog_title:      "वॉचडॉग खराबी",
    watchdog_details:    "त्रुटि विवरण",
    watchdog_missed_tag: "चूका हुआ टैग:",
    watchdog_last_tag:   "अंतिम देखा गया टैग:",
    watchdog_distance:   "तय की गई दूरी:",
    watchdog_time:       "समय:",
    watchdog_reset:      "मिशन रीसेट करें",
    watchdog_dismiss:    "बंद करें",
    watchdog_info:       "रोबोट टैग पहचानने में विफल रहा",
    watchdog_after:      "यात्रा के बाद",
    watchdog_from:       "टैग से",
    watchdog_check:      "छूटे हुए टैग पर रोबोट को एडजस्ट करें और फिर स्क्रीन पर रीसेट बटन दबाएं।",
    no_mission_trigger:  "ट्रिगर करने के लिए कोई मिशन लोड नहीं",
    trigger_success:     "मिशन सफलतापूर्वक ट्रिगर हुआ!",
    trigger_failed:      "मिशन ट्रिगर करने में विफल",
    trigger_error:       "ट्रिगर त्रुटि:",
    connected_toast:     "रोबोट से कनेक्ट हो गया",
    system_offline:      "सिस्टम ऑफलाइन",
    offline_no_load:     "सिस्टम ऑफलाइन — मिशन लोड नहीं हो सकता",
    select_first:        "पहले कृपया मिशन चुनें",
    loaded_success:      "सफलतापूर्वक लोड किया",
    load_failed:         "लोड करने में विफल",
    error_prefix:        "त्रुटि:",
    unknown_error:       "अज्ञात",
    command_sent:        "आदेश भेजा गया",
    command_failed:      "आदेश विफल",
    mission_started:     "मिशन शुरू हुआ",
    mission_paused:      "मिशन रोका गया",
    mission_resumed:     "मिशन फिर शुरू हुआ",
    mission_aborted:     "मिशन रद्द हुआ",
    mission_reset:       "मिशन रीसेट हुआ",
    mission_unloaded:    "मिशन अनलोड हुआ",
  },

  health: {
    amr: "एएमआर", imu: "आईएमयू", lidar: "लिडार", camera: "डेप्थ कैमरा",
    battery: "बैटरी", motor: "मोटर कंट्रोलर",
    front_estop: "फ्रंट इमरजेंसी स्टॉप", rear_estop: "रियर इमरजेंसी स्टॉप",
    encoder: "एन्कोडर", brakes: "ब्रेक",
    cpu: "सीपीयू उपयोग", memory: "मेमोरी उपयोग", disk: "डिस्क उपयोग",
    ros2: "ROS2 नोड्स", ros2t: "ROS2 टॉपिक्स", nav2: "Nav2 स्टैक",
    localization: "स्थान निर्धारण", pathplanner: "मार्ग योजनाकार",
    rosmaster: "ROS मास्टर", wifi: "वाई-फाई कनेक्शन",
    ethernet: "ईथरनेट", serial: "सीरियल संचार", can: "CAN संचार",
    position: "स्थिति", pendant_workover: "पेंडेंट वर्कओवर",
    front_estop1: "इमरजेंसी स्टॉप १ फ्रंट", front_estop2: "इमरजेंसी स्टॉप २ फ्रंट",
    rear_estop1: "इमरजेंसी स्टॉप १ रियर", rear_estop2: "इमरजेंसी स्टॉप २ रियर",
    pendant_estop: "पेंडेंट इमरजेंसी स्टॉप", fault_reset: "फॉल्ट रीसेट",
    front_lidar: "फ्रंट लिडार", rear_lidar: "रियर लिडार",
    front_bumper: "फ्रंट बंपर", rear_bumper: "रियर बंपर",
    auto_mode: "ऑटो मोड", manual_mode: "मैनुअल मोड",
    safety_interlocks: "सुरक्षा इंटरलॉक", lcp_mls_status: "एलसीपी और एमएलएस स्थिति",
    lcp1: "एलसीपी १", lcp2: "एलसीपी २", lcp3: "एलसीपी ३", mls: "एमएलएस",
    magnetic_agv: "मैग्नेटिक एजीवी", plc_status: "पीएलसी स्थिति",
    work_over: "वर्क ओवर", back_estop: "बैक इमरजेंसी स्टॉप", back_lidar: "बैक लिडार",
    status: { ok: "ठीक", fault: "दोष", idle: "निष्क्रिय", unknown: "अज्ञात", green: "हरा", red: "लाल" },
  },

  // ── REPORTS (Hindi) ───────────────────────────────────────
  report: {
    title:                    "रिपोर्ट",
    subtitle:                 "सुरक्षा इंटरलॉक घटनाएं और मिशन स्थिति इतिहास",
    rolling_window:           "रोलिंग",
    record_window:            "रिकॉर्ड विंडो",
    btn_interlock:            "इंटरलॉक",
    btn_mission:              "मिशन",
    btn_completed:            "पूर्ण",
    btn_combined:             "संयुक्त",
    btn_clear:                "साफ करें",
    robot_online:             "ऑनलाइन",
    robot_disconnected:       "डिस्कनेक्ट",
    state_label:              "स्थिति:",
    waiting_wifi:             "⚠ WiFi की प्रतीक्षा",
    card_interlock:           "इंटरलॉक",
    card_int_faults:          "इं. दोष",
    card_mission:             "मिशन",
    card_msn_faults:          "मि. दोष",
    card_tag_miss:            "टैग मिस",
    card_complete:            "पूर्ण",
    tab_interlock:            "इंटरलॉक",
    tab_mission:              "मिशन",
    tab_completed:            "पूर्ण",
    tab_miss_suffix:          "⚠",
    panel_interlock:          "🔒 इंटरलॉक घटना इतिहास",
    panel_mission:            "🚀 मिशन स्थिति इतिहास",
    panel_completed:          "✅ पूर्ण मिशन",
    records_label:            "रिकॉर्ड",
    badge_rolling:            "· रोलिंग",
    badge_tooltip_full:       "रोलिंग विंडो सक्रिय — नया रिकॉर्ड आने पर पुराना हटाया जाता है",
    badge_tooltip_slots:      "रोलिंग शुरू होने से पहले शेष स्लॉट",
    empty_interlock_label:    "अभी तक कोई इंटरलॉक घटना नहीं",
    empty_interlock_sub:      "सुरक्षा सिग्नल बदलने पर घटनाएं दिखती हैं",
    empty_mission_label:      "अभी तक कोई मिशन बदलाव नहीं",
    empty_mission_sub:        "मिशन स्थिति बदलने या टैग मिस होने पर घटनाएं दिखती हैं",
    empty_completed_label:    "अभी तक कोई पूर्ण मिशन नहीं",
    empty_completed_sub:      "मिशन COMPLETE होने पर सारांश जोड़ा जाता है",
    col_sr:                   "क्र.",
    col_timestamp:            "समय",
    col_signal:               "सिग्नल",
    col_status:               "स्थिति",
    col_health:               "स्वास्थ्य",
    col_value:                "मूल्य",
    val_active:               "⚠️ सक्रिय",
    val_normal:               "✅ सामान्य",
    val_fault_active:         "⚠️ दोष / सक्रिय",
    val_healthy:              "✅ स्वस्थ",
    col_state:                "स्थिति",
    col_tag_miss:             "टैग मिस",
    col_expected_got:         "अपेक्षित→मिला",
    col_mission_file:         "मिशन फ़ाइल",
    col_progress:             "प्रगति",
    col_speed:                "गति",
    col_action:               "क्रिया",
    col_safety:               "सुरक्षा",
    col_dist:                 "दूरी (मी)",
    val_miss:                 "⚠️ मिस",
    val_safety_active:        "⚠️ सक्रिय",
    val_safety_clear:         "✅ स्पष्ट",
    col_completed_at:         "पूर्ण हुआ",
    col_total_steps:          "कुल चरण",
    col_distance:             "दूरी (मी)",
    col_duration:             "अवधि",
    col_loop:                 "लूप",
    val_steps_suffix:         "चरण",
    val_loop_on:              "🔁 चालू",
    val_loop_off:             "— बंद",
    stat_total_events:        "कुल घटनाएं",
    stat_healthy:             "स्वस्थ",
    stat_faults:              "दोष",
    stat_state_changes:       "स्थिति बदलाव",
    stat_tag_misses:          "टैग मिस",
    stat_missions:            "मिशन",
    stat_complete:            "पूर्ण",
    stat_total_runs:          "कुल रन",
    stat_avg_steps:           "औसत चरण",
    stat_avg_dist:            "औसत दूरी (मी)",
    stat_loop_runs:           "लूप रन",
    alert_no_interlock:       "अभी तक कोई इंटरलॉक घटना नहीं।",
    alert_no_mission:         "अभी तक कोई मिशन घटना नहीं।",
    alert_no_completed:       "अभी तक कोई पूर्ण मिशन नहीं।",
    alert_no_data:            "अभी तक कोई घटना नहीं।",
    confirm_clear_all:        "सभी रिपोर्ट साफ करें (इंटरलॉक + मिशन + पूर्ण)?",
    csv_interlock_title:      "सुरक्षा इंटरलॉक घटना रिपोर्ट",
    csv_mission_title:        "मिशन स्थिति घटना रिपोर्ट",
    csv_completed_title:      "पूर्ण मिशन रिपोर्ट",
    csv_generated:            "उत्पन्न:",
    csv_showing_last:         "अंतिम दिखा रहा है",
    csv_records_rolling:      "रिकॉर्ड (रोलिंग विंडो)",
    csv_records_completed:    "पूर्ण मिशन",
    csv_tag_misses:           "टैग मिस:",
    csv_val_active:           "सक्रिय",
    csv_val_normal:           "सामान्य",
    csv_val_active_trig:      "सक्रिय/ट्रिगर",
    csv_val_inactive:         "निष्क्रिय/सामान्य",
    csv_val_yes:              "हाँ",
    csv_val_no:               "नहीं",
    csv_val_on:               "चालू",
    csv_val_off:              "बंद",
  },

  configure_task: "कार्य कॉन्फ़िगर करें",
  configure_task_desc: "चयनित कार्य के पैरामीटर कॉन्फ़िगर करें",
  mission_builder: "मिशन बिल्डर", loop: "लूप", infinite_loop: "(-१ = अनंत)",
  clear_all: "सभी साफ़ करें", select_robot: "रोबोट चुनें",
  drag_tasks_prompt: "मिशन बनाने के लिए कार्य मॉड्यूल यहाँ खींचें",
  total_tasks: "कुल कार्य", send_mission: "मिशन भेजें",
  tasks: "कार्य", available_tasks: "उपलब्ध कार्य",
  drag_drop_prompt: "मिशन में कार्य जोड़ने के लिए खींचें और छोड़ें",
  backend_status: "बैकएंड स्थिति",
  connected: "कनेक्टेड", disconnected: "डिस्कनेक्टेड",
  select_task: "कॉन्फ़िगर करने के लिए कार्य चुनें", configure: "कॉन्फ़िगर करें",
  direction: "दिशा", forward: "आगे", reverse: "पीछे",
  clockwise: "दक्षिणावर्त", anticlockwise: "वामावर्त",
  distance_meters: "दूरी (मीटर)", speed_ms: "गति (मी/से)",
  rotation_angle: "घूर्णन कोण (डिग्री)", angular_speed: "कोणीय गति (आर/से)",
  zone: "क्षेत्र", duration_ms: "अवधि (मिलीसेकंड)",
  backend_not_connected: "बैकएंड कनेक्ट नहीं है",
  select_robot_prompt: "कृपया रोबोट चुनें",
  add_task_prompt: "कम से कम एक कार्य जोड़ें",
  mission_queued: "मिशन सफलतापूर्वक कतारबद्ध किया गया",
  mission_failed: "मिशन भेजने में विफल",
};

// ── JAPANESE ─────────────────────────────────────────────────
const jpTranslations = {
  settings: "設定", robot_id: "ロボットID", dark_mode: "ダークモード",
  enable_notifications: "通知を有効にする", language: "言語", theme: "テーマ",
  save: "保存", reset: "リセット", settings_saved: "設定が正常に保存されました！",
  logout: "ログアウト", notifications: "通知",
  agvs: "AGV", robot_status: "ロボット状態",
  updated: "更新済み", never: "なし", loading: "読み込み中...",
  wifi_connected: "WiFi 接続済み", wifi_disconnected: "WiFi 未接続",
  select_online: "オンラインを選択", clear: "クリア",
  search_agvs: "AGV を検索...", agvs_selected: "AGV が選択されました",
  cancel: "キャンセル", confirm: "確認",
  missioncontrol: "ミッションコントロール", playpause: "再生/一時停止",
  dashboard: "ダッシュボード", magnetic: "インターロックダッシュボード",
  qrcode: "QRコード", maps: "マップ",
  realtime_visualisation: "リアルタイム表示",
  task_allocation: "タスク割り当て", health_check: "ヘルスチェック",
  reports: "レポート", mapview: "マップビュー",
  copyright: "© 2025 大気社インド | 無断転載禁止。",
  system_status: "システム状態", ros_bridge: "ROS ブリッジ",
  stations_loaded: "ステーション読込済み",
  current_location: "現在位置", target_location: "目標位置",
  amr_status_distribution: "AMR 状態分布",
  battery_level_overview: "バッテリー概要",
  amr_status: "AMR 状態", station_information: "ステーション情報",
  online: "オンライン", offline: "オフライン", running: "稼働中",
  idle: "待機中", maintenance: "メンテナンス", charging: "充電中",
  amr_id: "AMR ID", status: "状態", battery: "バッテリー",
  motor_temp: "モーター温度", speed: "速度", error: "エラー",

  mission_control: {
    title:               "ミッションコントロール",
    online:              "オンライン",
    offline:             "オフライン",
    mission_trigger:     "ミッショントリガー",
    triggering:          "トリガー中...",
    mission_file:        "ミッションファイル",
    select_mission:      "ミッションを選択...",
    missions_count:      "ミッション",
    waiting_list:        "ロボットからのミッション一覧を待機中...",
    start_mission:       "ミッション開始",
    starting:            "開始中...",
    missions_from_robot: "ロボットからのミッション",
    connect_to_see:      "利用可能なミッションを見るにはロボットに接続してください",
    loaded_badge:        "読込済み",
    loaded_mission:      "読込中のミッション",
    none:                "なし",
    state:               "状態",
    target_tag:          "目標タグ",
    speed_label:         "速度",
    progress:            "進捗",
    action:              "アクション",
    idle_action:         "待機",
        direction:           "方向",
    mission_progress:    "ミッション進捗",
    safety_label:        "安全",
    safety_active:       "作動中 — 停止中",
    safety_clear:        "クリア — 正常稼働",
    safety_warning:      "⚠ 安全条件が解除されるまで動作は無効です。",
    safety_banner:       "⚠ 安全システム作動中 — ロボット停止 ⚠",
    start:               "開始",
    pause:               "一時停止",
    resume:              "再開",
    abort:               "中止",
    reset_mission:       "ミッションリセット",
    unload_mission:      "ミッションアンロード",
    status_online:       "● オンライン",
    status_offline:      "○ オフライン",
    no_signal:           "信号なし",
    center_tag:          "タグを中央に",
    ready:               "準備完了 ✓",
    center_tag_btn:      "タグを中央に",
    center_tag_hint:     "「タグを中央に」をクリックして整列してください",
    align_backward:      "ロボットを後退させてください",
    align_forward:       "ロボットを前進させてください",
    align_right:         "ロボットを右に動かしてください",
    align_left:          "ロボットを左に動かしてください",
    align_finetune:      "位置を微調整してください",
    align_detail_y_back: "mm — Yが-1〜+1mmになるまで後退してください",
    align_detail_y_fwd:  "mm — Yが-1〜+1mmになるまで前進してください",
    align_detail_x_right:"mm — Xが-1〜+1mmになるまで右に動かしてください",
    align_detail_x_left: "mm — Xが-1〜+1mmになるまで左に動かしてください",
    align_detail_fine:   "mm — 両方が-1〜+1になるまでゆっくり調整してください",
    watchdog_title:      "ウォッチドッグ障害",
    watchdog_details:    "エラー詳細",
    watchdog_missed_tag: "見逃したタグ:",
    watchdog_last_tag:   "最後に確認したタグ:",
    watchdog_distance:   "移動距離:",
    watchdog_time:       "時刻:",
    watchdog_reset:      "ミッションリセット",
    watchdog_dismiss:    "閉じる",
    watchdog_info:       "ロボットがタグを検出できませんでした",
    watchdog_after:      "移動後",
    watchdog_from:       "タグから",
    watchdog_check:      "タグを読み取れなかった場合はロボットを調整し、画面上のリセットボタンを押してください。",
    no_mission_trigger:  "トリガーするミッションがロードされていません",
    trigger_success:     "ミッションが正常にトリガーされました！",
    trigger_failed:      "ミッションのトリガーに失敗しました",
    trigger_error:       "トリガーエラー:",
    connected_toast:     "ロボットに接続しました",
    system_offline:      "システムオフライン",
    offline_no_load:     "オフライン — ミッションをロードできません",
    select_first:        "先にミッションを選択してください",
    loaded_success:      "正常にロードされました",
    load_failed:         "ロードに失敗しました",
    error_prefix:        "エラー:",
    unknown_error:       "不明",
    command_sent:        "コマンド送信済み",
    command_failed:      "コマンド失敗",
    mission_started:     "ミッション開始しました",
    mission_paused:      "ミッションを一時停止しました",
    mission_resumed:     "ミッションを再開しました",
    mission_aborted:     "ミッションを中止しました",
    mission_reset:       "ミッションをリセットしました",
    mission_unloaded:    "ミッションをアンロードしました",
  },

  health: {
    amr: "AMR", imu: "IMU", lidar: "LiDAR", camera: "深度カメラ",
    battery: "バッテリー", motor: "モーター制御",
    front_estop: "前面非常停止", rear_estop: "後面非常停止",
    encoder: "エンコーダ", brakes: "ブレーキ",
    cpu: "CPU使用率", memory: "メモリ使用率", disk: "ディスク使用率",
    ros2: "ROS2ノード", ros2t: "ROS2トピック", nav2: "Nav2スタック",
    localization: "自己位置推定", pathplanner: "経路計画",
    rosmaster: "ROSマスター", wifi: "WiFi接続",
    ethernet: "イーサネット", serial: "シリアル通信", can: "CAN通信",
    position: "位置", pendant_workover: "ペンダントワークオーバー",
    front_estop1: "非常停止1 前面", front_estop2: "非常停止2 前面",
    rear_estop1: "非常停止1 後面", rear_estop2: "非常停止2 後面",
    pendant_estop: "ペンダント非常停止", fault_reset: "故障リセット",
    front_lidar: "前面LiDAR", rear_lidar: "後面LiDAR",
    front_bumper: "前面バンパー", rear_bumper: "後面バンパー",
    auto_mode: "オートモード", manual_mode: "マニュアルモード",
    safety_interlocks: "安全インターロック", lcp_mls_status: "LCP・MLS状態",
    lcp1: "LCP 1", lcp2: "LCP 2", lcp3: "LCP 3", mls: "MLS",
    magnetic_agv: "磁気AGV", plc_status: "PLC状態",
    work_over: "ワークオーバー", back_estop: "後面非常停止", back_lidar: "後面LiDAR",
    status: { ok: "正常", fault: "異常", idle: "待機", unknown: "不明", green: "緑", red: "赤" },
  },

  // ── REPORTS (Japanese) ────────────────────────────────────
  report: {
    title:                    "レポート",
    subtitle:                 "安全インターロックイベントとミッションステータス履歴",
    rolling_window:           "ローリング",
    record_window:            "レコードウィンドウ",
    btn_interlock:            "インターロック",
    btn_mission:              "ミッション",
    btn_completed:            "完了済み",
    btn_combined:             "統合",
    btn_clear:                "クリア",
    robot_online:             "オンライン",
    robot_disconnected:       "切断",
    state_label:              "状態:",
    waiting_wifi:             "⚠ WiFi待機中",
    card_interlock:           "インターロック",
    card_int_faults:          "インタ異常",
    card_mission:             "ミッション",
    card_msn_faults:          "ミッシ異常",
    card_tag_miss:            "タグミス",
    card_complete:            "完了",
    tab_interlock:            "インターロック",
    tab_mission:              "ミッション",
    tab_completed:            "完了済み",
    tab_miss_suffix:          "⚠",
    panel_interlock:          "🔒 インターロックイベント履歴",
    panel_mission:            "🚀 ミッションステータス履歴",
    panel_completed:          "✅ 完了ミッション",
    records_label:            "件",
    badge_rolling:            "· ローリング",
    badge_tooltip_full:       "ローリングウィンドウ有効 — 新しい記録が来ると最古の記録が削除されます",
    badge_tooltip_slots:      "ローリング開始までの残りスロット",
    empty_interlock_label:    "インターロックイベントはまだありません",
    empty_interlock_sub:      "安全信号が変化するとイベントが表示されます",
    empty_mission_label:      "ミッション状態変化はまだありません",
    empty_mission_sub:        "ミッション状態変化またはタグミス検出時にイベントが表示されます",
    empty_completed_label:    "完了ミッションはまだありません",
    empty_completed_sub:      "ミッションがCOMPLETE状態になるたびに行が追加されます",
    col_sr:                   "No.",
    col_timestamp:            "時刻",
    col_signal:               "信号",
    col_status:               "状態",
    col_health:               "健全性",
    col_value:                "値",
    val_active:               "⚠️ 作動中",
    val_normal:               "✅ 正常",
    val_fault_active:         "⚠️ 異常/作動中",
    val_healthy:              "✅ 正常",
    col_state:                "状態",
    col_tag_miss:             "タグミス",
    col_expected_got:         "期待→取得",
    col_mission_file:         "ミッションファイル",
    col_progress:             "進捗",
    col_speed:                "速度",
    col_action:               "アクション",
    col_safety:               "安全",
    col_dist:                 "距離 (m)",
    val_miss:                 "⚠️ ミス",
    val_safety_active:        "⚠️ 作動中",
    val_safety_clear:         "✅ クリア",
    col_completed_at:         "完了日時",
    col_total_steps:          "総ステップ",
    col_distance:             "距離 (m)",
    col_duration:             "所要時間",
    col_loop:                 "ループ",
    val_steps_suffix:         "ステップ",
    val_loop_on:              "🔁 ON",
    val_loop_off:             "— OFF",
    stat_total_events:        "総イベント",
    stat_healthy:             "正常",
    stat_faults:              "異常",
    stat_state_changes:       "状態変化",
    stat_tag_misses:          "タグミス",
    stat_missions:            "ミッション",
    stat_complete:            "完了",
    stat_total_runs:          "総実行",
    stat_avg_steps:           "平均ステップ",
    stat_avg_dist:            "平均距離 (m)",
    stat_loop_runs:           "ループ実行",
    alert_no_interlock:       "インターロックイベントはまだありません。",
    alert_no_mission:         "ミッションイベントはまだありません。",
    alert_no_completed:       "完了ミッションはまだありません。",
    alert_no_data:            "イベントはまだありません。",
    confirm_clear_all:        "全てのレポートをクリアしますか（インターロック + ミッション + 完了）？",
    csv_interlock_title:      "安全インターロックイベントレポート",
    csv_mission_title:        "ミッションステータスイベントレポート",
    csv_completed_title:      "完了ミッションレポート",
    csv_generated:            "生成日時:",
    csv_showing_last:         "最新",
    csv_records_rolling:      "件 (ローリングウィンドウ)",
    csv_records_completed:    "件の完了ミッション",
    csv_tag_misses:           "タグミス:",
    csv_val_active:           "作動中",
    csv_val_normal:           "正常",
    csv_val_active_trig:      "作動中/トリガー",
    csv_val_inactive:         "非作動/正常",
    csv_val_yes:              "はい",
    csv_val_no:               "いいえ",
    csv_val_on:               "ON",
    csv_val_off:              "OFF",
  },

  configure_task: "タスク設定",
  configure_task_desc: "選択したタスクのパラメータを設定します",
  mission_builder: "ミッションビルダー", loop: "ループ", infinite_loop: "(-1 = 無限)",
  clear_all: "すべてクリア", select_robot: "ロボットを選択",
  drag_tasks_prompt: "タスクモジュールをここにドラッグしてミッションを構築",
  total_tasks: "総タスク数", send_mission: "ミッション送信",
  tasks: "タスク", available_tasks: "利用可能なタスク",
  drag_drop_prompt: "ドラッグ＆ドロップでタスクをミッションに追加",
  backend_status: "バックエンド状態",
  connected: "接続済み", disconnected: "未接続",
  select_task: "設定するタスクを選択", configure: "設定",
  direction: "方向", forward: "前進", reverse: "後退",
  clockwise: "時計回り", anticlockwise: "反時計回り",
  distance_meters: "距離 (メートル)", speed_ms: "速度 (m/秒)",
  rotation_angle: "回転角度 (度)", angular_speed: "角速度 (r/秒)",
  zone: "ゾーン", duration_ms: "時間 (ミリ秒)",
  backend_not_connected: "バックエンドに接続されていません",
  select_robot_prompt: "ロボットを選択してください",
  add_task_prompt: "少なくとも1つのタスクを追加してください",
  mission_queued: "ミッションが正常にキューに入れられました",
  mission_failed: "ミッションの送信に失敗しました",
};

const translations = { en: defaultTranslations, mr: mrTranslations, hi: hiTranslations, jp: jpTranslations };

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    try {
      const local = localStorage.getItem('language');
      if (local && ['en', 'mr', 'hi', 'jp'].includes(local)) return local;
      const session = sessionStorage.getItem('language');
      if (session && ['en', 'mr', 'hi', 'jp'].includes(session)) return session;
      for (let cookie of document.cookie.split(';')) {
        const [name, value] = cookie.trim().split('=');
        if (name === 'language' && ['en', 'mr', 'hi', 'jp'].includes(value)) return value;
      }
      const browser = navigator.language?.split('-')[0];
      if (browser && ['en', 'mr', 'hi', 'jp'].includes(browser)) return browser;
    } catch (e) { console.warn('Error reading language:', e); }
    return 'en';
  });

  const [translationsData, setTranslationsData] = useState(translations[language]);
  const [isMobile, setIsMobile] = useState(false);
  const [updateKey, setUpdateKey] = useState(0);

  useEffect(() => {
    const check = () => {
      setIsMobile(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || window.innerWidth <= 768);
    };
    check();
    window.addEventListener('resize', check);
    return () => window.removeEventListener('resize', check);
  }, []);

  useEffect(() => {
    const onStorage = (e) => { if (e.key === 'language' && e.newValue && e.newValue !== language) setLanguageState(e.newValue); };
    const onChanged = () => setUpdateKey(p => p + 1);
    window.addEventListener('storage', onStorage);
    window.addEventListener('languageChanged', onChanged);
    return () => { window.removeEventListener('storage', onStorage); window.removeEventListener('languageChanged', onChanged); };
  }, [language]);

  useEffect(() => {
    setTranslationsData(translations[language]);
    try {
      localStorage.setItem('language', language);
      sessionStorage.setItem('language', language);
      document.cookie = `language=${language}; path=/; max-age=31536000; SameSite=Strict`;
      window.dispatchEvent(new CustomEvent('languageChanged', { detail: { language } }));
      window.dispatchEvent(new StorageEvent('storage', { key: 'language', newValue: language, oldValue: null, url: window.location.href }));
    } catch (e) { console.warn('Error saving language:', e); }
  }, [language]);

  const t = useCallback((key) => {
    if (!key) return '';
    try {
      const keys = key.split('.');
      let result = translationsData;
      for (const k of keys) {
        if (result && typeof result === 'object' && k in result) result = result[k];
        else { console.warn(`Translation missing: "${key}"`); return key.split('.').pop(); }
      }
      return result || key.split('.').pop();
    } catch (e) { return key.split('.').pop(); }
  }, [translationsData]);

  const setLanguage = useCallback((lang) => {
    if (!['en', 'mr', 'hi', 'jp'].includes(lang)) { console.warn(`Invalid language: ${lang}`); return; }
    if (lang !== language) setLanguageState(lang);
  }, [language]);

  const refreshTranslations = useCallback(() => {
    setUpdateKey(p => p + 1);
    setTranslationsData(p => ({ ...p }));
  }, []);

  const value = useMemo(() => ({
    language, setLanguage, t, isMobile, updateKey, refreshTranslations
  }), [language, setLanguage, t, isMobile, updateKey, refreshTranslations]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};